server:
  port: 9091

spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/paymentdb


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka   

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.SQL: DEBUG
custom:
  message: "Hello from payment-service"
